[project]
name = "resume-screening-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Animesh Jha", email = "animeshjha95166@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "gunicorn>=26.2.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pypdf>=6.19.0",
    "scikit-learn>=1.9.1",
]

[project.scripts]
resume-screening-system = "resume_screening_system:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
